### ISSUE TITLE
User automatically logged in before activating the account during registration

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#588] opened 2015-11-03 17:41 UTC
# Steps
1. Visit https://apinf.io
2. Click on sign up button
3. Enter the email address
4. Enter  the password
5. Click on Register button
6. Check the email instructions to activate the account
7. Do not click on 'activate account ' button 
# Findings

User logged in immediately after clicking on 'Register' button  before  the user could check email instruction to activate account.

**Comment by saralavanip** [comment] 2016-10-25 12:32
@bajiat , verified this issue on https://apinf.io and it is not reproducible.  

- Verified on https://nightly. apinf.io : User is automatically logged in when clicked on 'Register' button. Email not sent to user for verification.

**Comment by nnn** [comment] 2017-02-09 14:02
@saralavanip please confirm, couldn't reproduce it on nightly/staging/apinf.io.

**Comment by bajiat** [comment] 2017-03-29 10:55
@saralavanip Please verify. If not reproducible, close the issue. If reproducible, leave open and comment.

**Closed** 2017-03-29 11:40 UTC
Labels: bug, icebox
