### ISSUE TITLE
Reset password : 'Internal server error'

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1742] opened 2016-10-10 13:43 UTC
Steps:

1. Visit https://nightly.apinf.io    
2. Click on 'Login'      
3. Enter username     
4. Click on 'Forgot password'      

Expected Result: Send reset password link to the given email address.
Actual Result: Displays 'Internal Server Error'    

Browser:   
1. Mozilla Firefox 48.0   
(Mozilla Firefox for Ubuntu Canonical – 1.0 )     
2. Google Chrome 52.0.2743.116  

Operating System: Ubuntu 16.0 LTS

Screenshot:    
![selection_010](https://cloud.githubusercontent.com/assets/13309358/19238060/703df172-8f08-11e6-99f7-3732edfec4a8.jpg)

**Comment by bajiat** [comment] 2016-10-11 14:10
Duplicate of #1692 ?

**Comment by marla-singer** [comment] 2016-10-11 14:15
@bajiat In my opinion, not at all. There are two different tasks:

1. When email settings are enabled,  Reset password : 'Internal server error' (this issue)

2. When email settings are disabled: (1692 issue)

-  'Reset password link' not sent to the given (registered) email address

-  Displays successful message 'Email Sent'

**Comment by brylie** [comment] 2016-10-12 11:01
I am working on this issue, and will disable the *forgot password* link when email is not configured.

**Closed** 2016-10-13 15:17 UTC
Labels: bug, in progress
