### ISSUE TITLE
Plan for automated APInf API testing

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2443] opened 2017-04-11 12:58 UTC
# Goal
- Document about running automated testing for the APInf REST API.

Related to #2446

**Comment by bajiat** [comment] 2017-04-18 08:48
@mauriciovieira Could you help with this task? We can co-assign others, if needed.

**Comment by brylie** [comment] 2017-04-28 12:39
Closing as duplicate of #2446. REST API tests fall under the general automated testing plan.

**Closed** 2017-04-28 12:39 UTC
Labels: Apinf REST APIs, Architecture needed, icebox
