### ISSUE TITLE
Multiple confirmation texts shown at once when copying API key

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#1648] opened 2016-09-27 11:04 UTC
On nightly.
Add 2 API backends. Navigate to the first one. Copy the API key by clicking on the green "get API key" button.
> API key copied to clipboard.

Navigate to the second API. Copy the API key. Notice you get the confirmation message shown twice.
> API key copied to clipboard.
> API key copied to clipboard.

Navigate back to the first API. Copy the API key. Notice you get the confirmation message shown 3 times.
> API key copied to clipboard.
> API key copied to clipboard.
> API key copied to clipboard.

Etc.

**Comment by bajiat** [comment] 2016-09-28 07:35
Related to or duplicate of #1567

**Comment by bajiat** [comment] 2016-09-29 08:30
@jykae Would you have time to look at this? There should be examples to follow in other click handlers

**Comment by marla-singer** [comment] 2016-09-29 12:47
@bajiat I fixed it before -- https://github.com/apinf/platform/issues/1612
Please @philippeluickx  verify these again. Maybe nightly had an old source code

**Comment by bajiat** [comment] 2016-09-29 14:01
Nightly did have an old version, which Shaliko has fixed today.

**Comment by bajiat** [comment] 2016-09-30 07:18
@marla-singer I checked this today from nightly. If you reproduce the steps by Philippe, you do get multiple confirmations. When you copy API key once, you only get one confirmation, but if you navigate to another API and then copy API key, you will get two confirmations. And so on...

**Comment by bajiat** [comment] 2016-09-30 07:18
![screenshotfor1648](https://cloud.githubusercontent.com/assets/11626388/18983725/4203582e-86f7-11e6-81e3-4d7eb43d6b63.png)

**Comment by bajiat** [comment] 2016-10-07 09:42
@marla-singer Since the other issue I proposed to you was already resolved, could you take a look at this?

**Comment by marla-singer** [comment] 2016-10-07 10:38
@bajiat Tested this at nightly like user with administrator role and manager role.
**OS Debian 8
Browser: Chrome 52** 
Can't repeat this. It works as expected. Screenshots below:

1. Add two apis: 01 api and 02 api. Set proxy settings
![joxi_screenshot_1475836037763](https://cloud.githubusercontent.com/assets/20643403/19187174/adb0b42c-8c92-11e6-8b47-bbc88e0f0d1d.png)
![joxi_screenshot_1475836075853](https://cloud.githubusercontent.com/assets/20643403/19187182/b442c262-8c92-11e6-8e4c-c4fa6a6b8f72.png)
2. Go to "01 api" via Catalog and click "Copy api key". Result:
![joxi_screenshot_1475836118052](https://cloud.githubusercontent.com/assets/20643403/19187220/e307d466-8c92-11e6-9bec-0f5ab0326bcc.png)
3. Go to "02 api"  via Catalog and click "Copy api key". Result:
![joxi_screenshot_1475836165068](https://cloud.githubusercontent.com/assets/20643403/19187225/ea92ec0c-8c92-11e6-829f-8dd1e7de00f3.png)

**Closed** 2016-10-11 14:11 UTC
Labels: bug
