### ISSUE TITLE
When sharing API link in Slack, returns i18n code in string.

### ISSUE THREAD

**Issue by jykae** [apinf/platform#718] opened 2015-12-15 16:21 UTC
Site "Subtitle" is returned like:

```
"function () {return TAPi18n.__("configSubtitle");}”
```

![screenshot](https://cloud.githubusercontent.com/assets/1927158/12675984/20b5baa2-c697-11e5-9849-c3ad9afe907e.png)
# Definition of done
- [ ] [`subtitle`](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/_config.js#L8-L10) field/function has been removed from `/lib/_config/_config.js` (issue #786)
- [x] Site subtitle is retrieved from Branding collection
- [ ] Site subtitle is added to header in onCreated callback for page template(s) (issue #810)

**Comment by brylie** [comment] 2015-12-16 10:26
@jykae what link did you share on Slack? What i18n code are you referencing in the config file? Which unused fields?

**Comment by brylie** [comment] 2015-12-16 10:29
I found code in our [/lib/_config/_config.js](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/_config.js#L5-L10) file that may be what @jykae mentions. @elnzv, will this be replaced as part of the branding PR/branch?

**Comment by elnzv** [comment] 2015-12-16 10:35
@brylie, no, it won't.
Potentially, we can move this config to Meteor.settings public section.

**Comment by brylie** [comment] 2015-12-16 10:47
OK, cool. This would be a good setting for the settings page.

I am still unsure why it is failing in the original bug report.

**Comment by kyyberi** [comment] 2015-12-16 15:56
I took url from apika service for one api and pasted it to slack. This is the result 

![image](https://cloud.githubusercontent.com/assets/1927158/11845811/3fede73c-a41e-11e5-82af-87fe9c0b9095.jpeg)

**Comment by brylie** [comment] 2015-12-16 21:20
This may be caused by the client side template rendering of Blaze. We will have to research how to perform search engine optimization and/or server side rendering of anonymous templates.

I am removing the Apika PoC label, as the Apika label is our general purpose label for Apika related tasks, while Apika PoC are the essential tasks agreed to in the minimum viable product document.

**Comment by brylie** [comment] 2015-12-16 21:29
I think this will be resolved by completing task 152. I labelled 152 as Apika, so that we can track its progress as part of the Apika initiative.

**Comment by elnzv** [comment] 2016-01-29 10:27
Tested. Everything works as expected.
@kyyberi, please confirm.

**Comment by brylie** [comment] 2016-01-29 10:45
@elnzv on what branch did you test?

**Comment by elnzv** [comment] 2016-01-29 10:47
I took apinf.io link to test.

On Fri, 29 Jan 2016, 12:45 Brylie Christopher Oxley <
notifications@github.com> wrote:

> @elnzv <https://github.com/elnzv> on what branch did you test?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apinf/api-umbrella-dashboard/issues/718#issuecomment-176689024>
> .
>
-- 

Illya Nizyev ~ www.nzv.nz

**Comment by brylie** [comment] 2016-01-29 10:54
OK, great! I wonder what has changed, so that it works now. There is only [one file in our codebase where the site title and description are set](https://github.com/apinf/api-umbrella-dashboard/blob/develop/lib/_config/seo.js#L6-L7).

**Comment by brylie** [comment] 2016-01-29 10:55
I have [opened an issue](https://github.com/apinf/api-umbrella-dashboard/issues/809) to consider deprecating the SEO package, or at least set page titles from within individual page template rendered() callbacks.

**Comment by brylie** [comment] 2016-01-29 10:58
@jykae and/or @kyyberi is it alright that we close this issue?

**Comment by kyyberi** [comment] 2016-01-29 12:47
I get the same from apika. Did not test with apinf

![screenshot from 2016-01-29 14 46 19](https://cloud.githubusercontent.com/assets/1927158/12675985/20c111ae-c697-11e5-9ce4-75c3c06945bf.png)
![screenshot from 2016-01-29 14 45 53](https://cloud.githubusercontent.com/assets/1927158/12675984/20b5baa2-c697-11e5-9849-c3ad9afe907e.png)

**Comment by brylie** [comment] 2016-01-29 13:19
OK, we are taking this task up in the next sprint, most likely.

**Comment by elnzv** [comment] 2016-02-09 15:23
Related code was merged today.
Will test tomorrow it on remote, if issue still exists.

**Comment by elnzv** [comment] 2016-02-11 13:22
Fixed. You can test it by sharing this URL https://nightly.apinf.io/.
Couldn't get link preview in Slack, but Facebook Messenger shows preview correctly, with the right page title.

**Comment by kyyberi** [comment] 2016-02-25 17:25
Half victory if FB behaves right

**Comment by Nazarah** [comment] 2018-10-19 10:48
Closing this issue.

**Closed by Nazarah** 2018-10-19 10:48 UTC
Labels: bug, icebox
