### ISSUE TITLE
API Umbrella 0.14.0 : Dashboard analytics not shown after successful API call

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2450] opened 2017-04-12 12:48 UTC
Purpose: Testing 'API Umbrella 0.14.0'  on nightly.apinf.io  

# Steps  
1.Visit https://nightly.apinf.io   (v 0.42.0)  
2.Login as admin   
3.Add new API   
4.Connect API to proxy: 'API Umbrella 0.14.0' 
5.Get API key  
6.Call API   
7.Check analytics   

# Findings 
Analytics not shown after successful API call, shows user info text "Fetching latest data..."      

# Screenshot  
![call_api_new_proxy](https://cloud.githubusercontent.com/assets/13309358/24958167/13b1fffa-1f97-11e7-942b-2151cfe9ccc9.PNG)

**Comment by bajiat** [comment] 2017-05-15 08:12
@brylie Task is to investigate. Let's re-estimate and perhaps re-assign based on your investigation.

**Comment by brylie** [comment] 2017-05-17 07:43
In trying to reproduce this issue, I encountered an error when trying to log in to our API Umbrella instance:

```
Secure Connection Failed

An error occurred during a connection to metatavu-restapi-proxy1.apinf.io:80. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

![peek 2017-05-17 10-41](https://cloud.githubusercontent.com/assets/17307/26143421/871007e6-3aed-11e7-849d-e0ffb9aaa4e3.gif)

I would like to log in to https://nightly.apinf.io:3004/, so that I can verify that the API created on APInf is also created on API Umbrella 0.14.x deployment.

cc: @shaliko @bajiat

**Comment by shaliko** [comment] 2017-05-17 08:11
@saralavanip Issue fixed.

The issue was that I used own GitHub OAuth app credentials for setup second api-umbrella (0.14.0). Thanks @brylie for help me fix it.

**Comment by brylie** [comment] 2017-05-17 08:42
After gaining access to the Nightly API Umbrella 0.14, I see there are two configured API Backends:

![screenshot_20170517_114119](https://cloud.githubusercontent.com/assets/17307/26145623/c2b7eab8-3af5-11e7-8ba8-779ec26f1404.png)

I added the **Analytics Test** backend. Next, I will make some calls to that endpint to see if analytics are recorded.

**Comment by brylie** [comment] 2017-05-17 08:48
## Request works
Making a request to the Analytics Test endpoint works properly, returning the **Google search** page that is configured as the backend:

![screenshot_20170517_114434](https://cloud.githubusercontent.com/assets/17307/26145732/349d87fa-3af6-11e7-88e3-13aea8013709.png)

## Analytics work
API Umbrella records analytic(s) for the request(s) to the `/analytics-test/` endpoint:

![screenshot_20170517_114711](https://cloud.githubusercontent.com/assets/17307/26145820/932f4cae-3af6-11e7-98d1-10e31857754d.png)

**Comment by brylie** [comment] 2017-05-17 08:55
## Dashboard errors
The APInf dashboard view for the **Analytics Test** endpoint behaves as described in the issue, stopping during the **Fetching data** phase.

![screenshot_20170517_115046](https://cloud.githubusercontent.com/assets/17307/26145932/12b24026-3af7-11e7-81b1-d88d6dc7698a.png)

## Console errors
Several messages appear in the browser console.

### getElasticSearchData method
```js
Exception in delivering result of invoking 'getElasticSearchData': TypeError: Cannot read property 'hits' of undefined
```

### Elasticsearch
```js
{
  error: "[query_phase_execution_exception] Result window is… [index.max_result_window] index level parameter.", reason: undefined, details: undefined, 
  message: "[[query_phase_execution_exception] Result window i…[index.max_result_window] index level parameter.]", errorType: "Meteor.Error"…}
details
:
undefined
error
:
"[query_phase_execution_exception] Result window is too large, from + size must be less than or equal to: [10000] but was [50000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter."
errorType
:
"Meteor.Error"
message
:
"[[query_phase_execution_exception] Result window is too large, from + size must be less than or equal to: [10000] but was [50000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.]"
reason
:
undefined
```

**Comment by brylie** [comment] 2017-05-17 09:06
This seems to be related to our [hard-coded query limit](https://github.com/apinf/platform/blob/develop/elasticsearch/server/methods.js#L60). 

We have work-in-progress to refactor the Dashboard code, including removing the 50,000 result limit:
- https://github.com/apinf/platform/issues/2557
- https://github.com/apinf/platform/issues/2556

A stop-gap solution would be to remove the hard-coded limit while refactoring the Dashboard.

cc: @bajiat @frenchbread @marla-singer

**Comment by bajiat** [comment] 2017-08-07 11:36
Closing, since we are re-making the dashboard without a query limit.

**Closed by bajiat** 2017-08-07 11:36 UTC
Labels: bug, ready, wontfix

**Comment by marla-singer** [comment] 2017-09-08 09:21
@bajiat @brylie Verified it in a new Dashboard and it works as expected
![joxi_screenshot_1504862215531](https://user-images.githubusercontent.com/20643403/30205003-2ccab892-9490-11e7-9915-a61145b81b38.png)
