### ISSUE TITLE
Tableview of catalogue throws error in console

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#1642] opened 2016-09-27 10:45 UTC
On nightly. Go to catalogue, switch to tableview. Error message in console:

`GET https://nigtly.apinf.io/gridfs/ApiLogo/md5/c720157c0c8d49a3f7b4445dc9d8e7b0 net::ERR_NAME_NOT_RESOLVED`

**Comment by bajiat** [comment] 2016-09-29 08:36
@saralavanip Can you try to reproduce?

**Comment by saralavanip** [comment] 2016-09-30 09:28
@bajiat, verified on https://nightly.apinf.io  , couldn't reproduce this issue. 

Screenshot:  
![catalog_table_view](https://cloud.githubusercontent.com/assets/13309358/18987206/3eae1242-8709-11e6-8899-4d396c30b774.png)

**Comment by bajiat** [comment] 2016-10-20 12:11
Cannot reproduce either. Closing the issue.

**Closed** 2016-10-20 12:12 UTC
Labels: bug
