### ISSUE TITLE
API request timeline in Dasboard is empty even if there are recent calls to display

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2062] opened 2017-02-06 10:49 UTC
_From @bajiat on January 17, 2017 11:26_

# Steps to reproduce
1. Sign in to nightly.apinf.io as admin
2. Make calls to any API
3. Go to dashboard and check whether the calls you made in step 2 can be viewed

# Expected result
The calls made in step 2 are visible in charts and in table

# Actual result
API Request Timeline is empty. Other charts and the table show the calls made to the API

Screenshots in Comments.

_Copied from original issue: Digipalvelutehdas/APIKA#245_

**Comment by bajiat** [comment] 2017-02-06 10:49
Making calls to TAMK reservations API:

<img width="946" alt="postman screenshot" src="https://cloud.githubusercontent.com/assets/11626388/22018785/4950e070-dcb9-11e6-8ead-e971ebfc2f78.png">

Viewing the dashboard for TAMK reservations:

<img width="467" alt="api request timeline" src="https://cloud.githubusercontent.com/assets/11626388/22018800/5c6a8878-dcb9-11e6-915f-ba1ada91fa7d.png">

**Comment by bajiat** [comment] 2017-02-06 10:49
Same result with Hello Apinf API (called from the Swagger file)

<img width="477" alt="dashboard for hello apinf api" src="https://cloud.githubusercontent.com/assets/11626388/22018962/0e1ac4de-dcba-11e6-8069-50090b55919f.png">

**Comment by bajiat** [comment] 2017-02-06 10:49
The time interval was so small that the first calls were not shown. When more calls were made in an hour there was something to see.

**Comment by marla-singer** [comment] 2017-09-12 14:34
@bajiat Have to be fixed in a new Dashboard

**Comment by marla-singer** [comment] 2017-12-07 10:32
@preriasusi The issue is outdated and can be closed because there is the new Dashboard module

**Closed** 2017-12-08 09:16 UTC
Labels: enhancement, icebox
