### ISSUE TITLE
Create a basic bug triaging process

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2632] opened 2017-06-07 08:31 UTC
In order to ensure timely response and resolution of bug reports, lets create a process we can use to triage bug reports. Examples include:

- [Steps to triage a bug](https://wiki.documentfoundation.org/QA/BugTriage#Steps_to_Triage_a_Bug)
- [Bug management/how to triage](https://www.mediawiki.org/wiki/Bug_management/How_to_triage)
- [How to hold a bug triage meeting](https://www.mediawiki.org/wiki/Bug_management/Meeting_preparations)

# Goal
Have a clear process that we can follow as a team to triage and resolve bug reports.
There are labels for bug severity/priority.

# Related
This issue came out of the discussion in issue #2622

**Comment by bajiat** [comment] 2017-06-08 08:00
We should create separate labels for bug priority/severity. I would like to select only one of those and not have Severity and Priority separately (compare with https://wiki.gnome.org/Bugsquad/TriageGuide, which has both)

What are the potential labels? Is this enough Blocker (or Showstopper), Critical, Major, Minor? 

Triaging should be a daily activity so that showstoppers can be identified. There should be at least one responsible person.

**Comment by ashakunt** [comment] 2017-06-08 08:04
> Triaging should be a daily activity so that showstoppers can be identified. There should be at least one responsible person.

Not necessarily a daily activity. A showstopper will be identified any way. At least the PO, Tech Lead, Error manager should go through open, non-resolved bugs and decide next steps, e.g. adding to sprint or not.

**Comment by bajiat** [comment] 2017-06-08 09:57
We could also have a separate column for bugs in Waffle, which would keep them separate from Prioritized backlog, which is for new implementation or enhancements.

**Comment by bajiat** [comment] 2017-08-09 12:17
Current draft of steps and priorities. Comments are welcome.

Next to be added: answers to **when** and **who** - when and how often should the triaging be done, who should participate.

## Steps
1. Find the bugs requiring triage
1. Check that each bug has been filed in correct repository
2. Check that each issue (bug reportI is not a duplicate of an existing bug report. 
   If it is a duplicate, mark it as one and close the issue.
3. Check that each issue contains required information so that it is possible to study and/or reproduce it: 
  * environment (e.g. OS, browser and its version)
  * steps to reproduce
  * expected result 
  * actual result
  * Preferably, also  a screenshot of the problem. 
  If there is missing information, ask the person who has filed the bug report to fill in the missing details.
4. Try to reproduce the bug.
5. Assign a priority label to the issue.
6. According to the priority, move the issue from Inbox to relevant column in Waffle.
7. Notify developers about bugs requiring immediate fix.

Note: If the problem is caused by a package not developed by the APInf team, make sure an upstream issue is created and referenced in the original report.

## Priority guidelines

Critical - Bug is in production, core functions are broken, requires immediate fixing
Major - Bug is in production, functions other than core functions are broken, affects multiple users
Minor - Bug is in development or is not very likely to occur

If the issue is an enhancement request rather than a bug report, re-label it as 'enhancement'.

**Comment by bajiat** [comment] 2017-08-17 10:41
# Bug triaging process

## Introduction
Weekly, mid week if possible
Two-person activity: Lead developer and product owner
Goal for later is to have an error manager role

## Steps
1. Find the bugs requiring triage in Github
1. Check that each bug has been filed in correct repository
2. Check that each issue (bug reportI is not a duplicate of an existing bug report. 
   If it is a duplicate, mark it as one and close the issue.
3. Check that each issue contains required information so that it is possible to study and/or reproduce it: 
  * environment (e.g. OS, browser and its version)
  * steps to reproduce
  * expected result 
  * actual result. 
  * Preferably, there should also be a screenshot of the problem. 
  If there is missing information, ask the person who has filed the bug report to fill in the missing details.
4. Try to reproduce the bug.
5. Assign a priority label to the issue.
6. According to the priority, move the issue from Inbox to relevant column in Waffle.
7. Notify developers about bugs requiring immediate fix.

Note: If the problem is caused by a package not developed by the APInf team, make sure an upstream issue is created and referenced in the original report.

## Priority guidelines

Critical - Bug is in production, core functions are broken, requires immediate fixing
Major - Bug is in production, functions other than core functions are broken, affects multiple users
Minor - Bug is in development or ??

If the issue is an enhancement request rather than a bug report, re-label it as 'enhancement'.

# Sentry triage

The Sentry Unresolved issue list must be groomed weekly by senior developers.

## Steps
1. Investigate the unresolved issues one by one
  - Figure out what is the original error, what module or line of code is involved and try to reproduce
2. Decide whether it is an error or not. Options:
  - Ignore, if not an error
  - Assign to someone else, if you cannot figure out the reason
  - Create an issue in Github, if it is an error that needs to be resolved
3. If you create an issue in Github
  - Link to the Sentry URL 
  - Provide relevant details in the issue, including steps to reproduce, based on the investigation
  - Leave out any sensitive information

**Comment by bajiat** [comment] 2017-08-17 10:41
@marla-singer Can you take a look at the Sentry triage process above and comment?

**Comment by marla-singer** [comment] 2017-08-17 12:28
@bajiat I've done the same instruction then I've looked at a bug on Sentry. Everything is find for me

**Comment by bajiat** [comment] 2017-08-21 11:57
@bajiat reminder to myself: Post to docs repo and close

**Closed** 2017-09-05 06:40 UTC
