### ISSUE TITLE
Generate SDK file displays error

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2487] opened 2017-04-24 08:18 UTC
# Steps  
1.Visit https://staging.apinf.io v 0.43.0 
2.Login 
3.Add API and connect it to proxy  (eg. staging/API-umbrella New)
4.Go to above added API   
5.Click on 'Documentation' tab 
6.Upload documentation file (eg.swagger.yaml)  
7.Go to 'SDK Generate'  
8.Select any language 
9.Click on 'Download'  

# Findings 
- API documentation view shows  a 'warning' message  
- Generate SDK file shows error "File not supported by Code Generator....."     

# Screenshot 
![upload_documentation_file_info_warning](https://cloud.githubusercontent.com/assets/13309358/25328129/5c86ef3c-28df-11e7-973d-3892cde61696.PNG)       

![generate_sdk_file_error_msg1](https://cloud.githubusercontent.com/assets/13309358/25328136/6925c718-28df-11e7-8877-680efd861b0f.PNG)

**Comment by marla-singer** [comment] 2017-04-24 15:12
@bajiat Duplicate of #2216

**Comment by saralavanip** [comment] 2017-05-12 12:45
Verified on staging v 0.44.0  and it is reproducible.

**Comment by bajiat** [comment] 2017-05-15 05:54
@saralavanip Can you check this in nightly and if not reproducible there, then close.

**Comment by saralavanip** [comment] 2017-05-15 07:22
@taija, verified this issue on nightly v  0.44.0 and it is reproducible.  

Screenshot: 
![nightly_generate_sdk_error](https://cloud.githubusercontent.com/assets/13309358/26046430/9128f89c-3957-11e7-8c5c-71da01f000d1.PNG)

**Comment by brylie** [comment] 2017-05-15 07:50
@saralavanip do you have an example swagger file we can use to test with? Which swagger / API are using to test?

**Comment by saralavanip** [comment] 2017-05-15 09:39
@brylie , downloaded  the example swagger files for testing from http://editor.swagger.io/  
eg. Uber API , Swagger Petstore

**Comment by brylie** [comment] 2017-05-15 09:55
It appears that our request to codegen.apinf.io might be missing the swagger specification file:

![peek 2017-05-15 12-53](https://cloud.githubusercontent.com/assets/17307/26052292/a760a3e2-396d-11e7-80e8-23ad1b8ad43d.gif)


```js
{code: 1, type: "error", message: "No swagger specification was supplied"}
code: 1
message: "No swagger specification was supplied"
type: "error"
```

**Closed** 2017-05-24 12:53 UTC
Labels: bug, in progress
