### ISSUE TITLE
Add item "Login patforms" in user menu

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2952] opened 2017-09-19 13:02 UTC
**Title**:

Add item "Login patforms" in user menu

**Description**:

On global settings page for site Administrator a new point appears "Login platforms"
Add this item in user menu to allow directly access to this page
![joxi_screenshot_1505825817295](https://user-images.githubusercontent.com/20643403/30593629-f67db1d2-9d53-11e7-8f53-7fbe8c7f7a6b.png)

**Comment by Nazarah** [comment] 2017-09-26 06:12
@marla-singer do we need an additional item in the site admin menu?
I believe all the options (Branding, Proxy, Settings, etc.) can be accessed when item Settings is clicked from the user menu.
Since this is part of settings and configuration, in my opinion adding this into user menu is redundant. :-/
What do u think?

**Comment by marla-singer** [comment] 2017-09-26 07:55
@Nazarah I thought it would be not bad so I created this issue. 
Anyway, the last word is yours and @bajiat

**Comment by bajiat** [comment] 2017-10-26 11:07
I think the dropdown menu and side menu should be identical.

**Comment by bajiat** [comment] 2017-10-26 11:09
Duplicate of bug report #3042. Closing.

**Closed by bajiat** 2017-10-26 11:09 UTC
Labels: duplicate, enhancement
