### ISSUE TITLE
Users view: users count shown in footer 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2681] opened 2017-06-22 09:16 UTC
# Steps  
1.Visit https://staging.apinf.io v 0.46.0 
2.Login as admin 
3.Navigate to 'Users' view  

# Findings  
Users count shown in footer  

# Screenshot  
![users_pagination_text_infooter](https://user-images.githubusercontent.com/13309358/27426407-4f83551c-5744-11e7-88d5-1a1c97719b6c.PNG)

**Comment by Nazarah** [comment] 2017-06-27 10:25
@saralavanip This is reproducible in nightly as well. There is an existing issue reported already.
https://github.com/apinf/platform/issues/2683

**Comment by bajiat** [comment] 2017-08-17 06:30
Closing as duplicate of #2683

**Closed by bajiat** 2017-08-17 06:30 UTC
Labels: bug, duplicate
