### ISSUE TITLE
Dismiss notification dialog handling error during reset / forgot password

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#574] opened 2015-11-03 16:37 UTC
# Steps
1. Visit https://apinf.io
2. Go to sign in page
3. Enter email address
4. Click on 'Forgot your password'
5. Click on 'Email Reset Link' button
6. Check email instruction and click on 'Reset password' button 
7. Enter the new password
8. Click on set password button
9. Dismiss notification dialog is shown
# Findings

 The home page after login is active before user 'dismiss' notification dialog.   
# Screenshot

![menu_page2_active_before_dismiss_dialoge](https://cloud.githubusercontent.com/assets/13309358/10914171/df61fe02-8259-11e5-85f3-b560b697a798.png)

**Comment by saralavanip** [comment] 2016-10-24 10:55
@bajiat , verified this issue on https://apinf.io and this is still reproducible. The user can navigate to other views for eg. 'Catalog' / Dashboard / 'Add API'  before the user 'dismiss' 'Password Reset' successful dialog.   

- This is a user experience issue and could be enhanced eg. displaying info banner with close icon instead of the 'Dismiss' dialog in the middle of the screen.   

Screenshots:    
![selection_029](https://cloud.githubusercontent.com/assets/13309358/19643039/e9e00c3e-99f0-11e6-99f8-f76f54ca5fdf.jpg)       

![selection_030](https://cloud.githubusercontent.com/assets/13309358/19643127/5881c06a-99f1-11e6-9636-6c4c90d7729c.jpg)  

![selection_032](https://cloud.githubusercontent.com/assets/13309358/19643058/fcbf3ab4-99f0-11e6-8b56-4a1021da1088.jpg)     

![selection_033](https://cloud.githubusercontent.com/assets/13309358/19643069/0aa85a7a-99f1-11e6-9045-59446cf17257.jpg)

**Comment by saralavanip** [comment] 2016-10-28 11:24
@bajiat , verified this issue on https://staging.apinf.io and it is reproducible.  

Screenshot:  
![selection_081](https://cloud.githubusercontent.com/assets/13309358/19804951/302ba172-9d1a-11e6-9067-0ca92c1cc4f1.jpg)

**Comment by nnn** [comment] 2017-02-09 14:00
Duplicate of https://github.com/apinf/platform/issues/575

**Comment by bajiat** [comment] 2017-03-29 10:44
Close as wontfix.

**Closed by bajiat** 2017-03-29 10:44 UTC
Labels: bug, duplicate, icebox
