### ISSUE TITLE
Runtime exception on dashboard getProxyData

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2040] opened 2017-02-06 10:19 UTC
_From @alfredjkwak on December 21, 2016 13:21_

```
=> Starting app on port 3000...
{"line":"106","file":"percolate_migrations.js","message":"Migrations: Not migrating, already at version 2","time":{"$date":1482167053954},"level":"info"}
spiderable: phantomjs not installed. Download and install from http://phantomjs.org/
Exception while invoking method 'getProxyData' TypeError: Cannot read property '0' of undefined
    at [object Object].getProxyData (dashboard/server/methods.js:25:39)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1711:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:707:46
    at Session.method (packages/ddp-server/livedata_server.js:681:23)
    at packages/ddp-server/livedata_server.js:551:43
```

Helpfult hint: Check proxyBackend has apiUmbrella object before using it https://github.com/Digipalvelutehdas/APIKA/blob/fec765d2deaa23dba58402a4cc3b2617709bc6a0/dashboard/server/methods.js#L25

_Copied from original issue: Digipalvelutehdas/APIKA#178_

**Comment by bajiat** [comment] 2017-02-06 10:19
# Steps to reproduce
1. Log into apika.digipalvelutehdas.fi as admin (v. 0.36 deployed)
2. Go to dashboard
3. Go to Select API list
4. select an API from the list
4. Check that the data was updated
5. Select another API from the list and see that the data is updated

Repeat step nr. 5 until you get 504 Gateway Time-out

Cannot tell whether it is a certain API that causes this or a certain nr of selections. Cannot detect any systematic error.

**Comment by marla-singer** [comment] 2017-09-07 12:06
@bajiat Have to be fixed in a new Dashboard

**Comment by marla-singer** [comment] 2017-12-07 09:42
@preriasusi The issue is outdated because now there is a new Dashboard module

**Comment by marla-singer** [comment] 2018-01-30 12:07
Closed it as outdated

**Closed by marla-singer** 2018-01-30 12:07 UTC
Labels: backlog, bug
