### ISSUE TITLE
Sign in with invalid email /password doesn't notify reason for error 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#587] opened 2015-11-03 17:39 UTC
# Steps
1. Visit https://apinf.io  
2. Go to sign in page  
3. Enter email address  
4. Enter  invalid password  
5. Click on 'sign in ' button  
# Expected Result

Sign in not successful  
# Findings
-  Sign in not successful 
-  User not notified the reason for error
-  Displays error message 'login forbidden'
# Screenshot:

![invalid_password_login_forbidden](https://cloud.githubusercontent.com/assets/13309358/10916083/72b8996a-8262-11e5-92dc-1df352e3c27d.png)

**Comment by bajiat** [comment] 2015-11-09 12:14
Check Meteor accounts UI (@brylie check the name) documentation. Check existing error strings and make them for user friendly. Add i18n tags.
Co-pilot: @elnzv.

**Comment by saralavanip** [comment] 2016-10-24 11:50
@bajiat  , verified this issue on https://apinf.io and https://nightly.apinf.io. This issue is reproducible.

Expected Result: User must be notified withe error message 'Invalid password'     
Actual Result: Displays error message 'Login forbidden'     

Screenshot:  
![selection_035](https://cloud.githubusercontent.com/assets/13309358/19644543/00067248-99f9-11e6-9749-11293fb3bd1a.jpg)   

![selection_036](https://cloud.githubusercontent.com/assets/13309358/19644576/2c34c9f0-99f9-11e6-9eb3-881d9de36463.jpg)

**Comment by brylie** [comment] 2016-10-24 12:03
The 'login forbidden' message may be ambiguous to prevent abuse. E.g. people may attempt to see if an email is registered on the site, using the login form as a 'search box'.

**Comment by nnn** [comment] 2017-02-06 13:22
@bajiat should we close this issue?

**Comment by bajiat** [comment] 2017-03-29 10:53
Closing as wontfix. It is by design as per the upstream package.

**Closed by bajiat** 2017-03-29 10:53 UTC
Labels: bug, icebox
