### ISSUE TITLE
Can't add an API using a valid json or yaml file

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3230] opened 2017-12-13 12:05 UTC
**Steps to Reproduce**: 
1. go to page: https://staging.apinf.io and login
2. click Add API
3. Scroll down to Add OpenAPI Specification
4. select 'File' from dropmenu
5. click choose file
6. select a valid json or yaml or yml file
7. click import                    

**Outcome**:
Red s-alert appears showing message: [[object object]]
API can't be added to the platform
http://recordit.co/6M107C1p0z
         
**Expected Behavior**:
It should be possible to add an API using a valid json or yaml file that contains atleast API name and URL.
User should be redirected to API profile.
                   
**Environment**:
Windows 10, Chrome browser (latest), APInf staging site (https://staging.apinf.io) - relase 0.52

**Comment by marla-singer** [comment] 2017-12-13 12:08
@Nazarah Provide a Swagger file that you tried to add

**Comment by Nazarah** [comment] 2017-12-13 12:09
Tested in nightly APInf and could not reproduce the error.
Description within the json or yaml file needs to be under 1000 characters. 

@marla-singer sharing the swagger in rocket chat as GitHub won't allow u to upload json/yaml file

**Comment by preriasusi** [comment] 2017-12-13 12:11
@Nazarah Is this again bebause of stagining?

**Comment by anarva** [comment] 2017-12-13 13:03
I'm close to the root cause: The docker container on staging has faulty DNS settings so that the request to get the json (Swagger) file is pointing to the wrong IP address. Nothing wrong with the app, if I'm correct. 

I'm working on fixing the DNS problem.

**Comment by marla-singer** [comment] 2017-12-13 14:15
I will test it again after resolving the problem with DNS settings. I got strong feeling that the error relates (about [object Object] message)

**Comment by anarva** [comment] 2017-12-13 15:21
Modified the platform docker image on staging: Removed staging.apinf.io reference on the last line of /etc/hosts file and now the error is fixed.

 @marla-singer, please verify and make other checks you see necessary.

**Comment by marla-singer** [comment] 2017-12-14 08:02
@Nazarah Please test it again. [object Object] error doesn;t appear

**Comment by Nazarah** [comment] 2017-12-15 08:19
@marla-singer Tested in both vamos.apinf.io and staging.apinf.io with release 0.52.
In vamos, I can add an API by uploading swagger file.
In APInf staging, i still got the problem [[object object]]
I cleaned the browser history before testing it.
Tested with Windows 10 and chrome.

**Closed** 2017-12-15 14:13 UTC
Labels: bug, in progress
