### ISSUE TITLE
Back button behaviour in mobile UX results to empty page

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2432] opened 2017-04-09 07:47 UTC
## Description

Back button in mobile UX not behaving as expected. Hitting back button results to empty page. 

## steps to reproduce 

- Go to nightly.apinf.io
- Open API profile page from the latest APIs
- Hit back button in browser. Browser goes to frontpage, but that is empty. 

https://www.dropbox.com/s/1qxbodf8xen8wp7/SVID_20170408_204300.mp4?dl=0

**Comment by bajiat** [comment] 2017-05-12 12:35
Could not reproduce either with Safari (iPhone) or with Firefox and Chrome (Huawei). Closing the issue.

**Closed** 2017-05-12 12:35 UTC
Labels: bug, Usability Issue
