### ISSUE TITLE
Login with invalid username or email displays 'Internal Server Error' message

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1808] opened 2016-10-24 12:31 UTC
# Steps:
1. Visit https://apinf.io  
2. Click on 'Login'  
3. Enter non-registered username or email address  
4. Enter valid password  
5. Click on 'Sign In' button  

# Expected Result
Notify user with error message 'Invalid email address'  

# Actual Result
Displays 'Internal Server' error    

# Findings
-  This scenario was also tested on https://nightly.apinf.io and the result is: displays error message 'Login forbidden'   (login unsuccessful )as expected.  

# Browser
1. Mozilla Firefox 48.0 
   (Mozilla Firefox for Ubuntu Canonical – 1.0 )   
2. Google Chrome 52.0.2743.116 

# Operating System
 Ubuntu 16.0 LTS   

# Screenshot
![selection_040](https://cloud.githubusercontent.com/assets/13309358/19645661/9085e33a-99fe-11e6-8279-4f94f98feaf9.jpg)  
![selection_041](https://cloud.githubusercontent.com/assets/13309358/19645681/a6adc88a-99fe-11e6-94f6-c2c29adb8634.jpg)

**Comment by bajiat** [comment] 2016-10-26 07:18
@brylie Can you check if anything has changed in validate (?) login code after release 0.33?

**Comment by brylie** [comment] 2016-10-26 07:20
There is a [`login_verify` function](https://github.com/apinf/platform/blob/develop/users/server/login_verify.js) that runs on the server when submitting the form. It is possible that recent changes to that file, or some other user login related file/configuration has resolved this issue in nightly.

**Comment by bajiat** [comment] 2016-10-28 08:29
@jykae Please check this one after apinf.io is redeployed and settings have been changed

**Comment by jykae** [comment] 2016-10-31 11:34
@bajiat Still results "Internal server error" in apinf.io

<img width="1272" alt="nayttokuva 2016-10-31 kello 13 33 34" src="https://cloud.githubusercontent.com/assets/293452/19852890/b8525068-9f6e-11e6-9ca9-fea6ca2cc044.png">

**Comment by brylie** [comment] 2016-10-31 11:39
I think this is by design. If we send an invalid email address, the security method may be designed to throw a 500 error to the client.

**Comment by jykae** [comment] 2016-10-31 11:43
@brylie yep, error is ok, but we should find a way to catch error and show nicer error message for user :)

**Comment by brylie** [comment] 2016-10-31 11:44
Also, the login form allows people to login with a username, so we can't always expect an email address.

**Comment by jykae** [comment] 2016-10-31 11:46
@brylie Right, but it behaves same way if username does not exist on apinf.io

**Comment by brylie** [comment] 2016-10-31 11:47
Where does the error originate? What method is checking that the user exists?

**Comment by brylie** [comment] 2016-10-31 11:49
And what is the difference between our local envoronment, where we see 'Login forbidden' and the deployment, where we see 'Internal server error'?

**Comment by jykae** [comment] 2016-10-31 11:49
@brylie Don't know, trying to look at it.. in progress

**Comment by brylie** [comment] 2016-10-31 11:49
I am testing locally with `meteor --production` to see if there are any console errors.

**Comment by jykae** [comment] 2016-10-31 11:54
This does not look too good, https://github.com/apinf/platform/blob/develop/users/server/accounts_hooks.js#L38
but it has worked somehow in the past :D

**Comment by brylie** [comment] 2016-10-31 11:56
Hm. That seems to be left over from our boilerplate. Is it still necessary, or can we remove it?

**Comment by brylie** [comment] 2016-10-31 11:58
Also, how can we access the server error log? It would probably be useful to get an error message.

**Comment by jykae** [comment] 2016-10-31 12:01
@brylie I asked @shaliko to look server logs

**Comment by brylie** [comment] 2016-10-31 12:19
Kool beans.

**Comment by jykae** [comment] 2016-10-31 12:48
@brylie onLogin hook seems to be unnecessary, tested locally by commenting out, tried to register/login both with Github. It should wipe away undefined user._id error found in server logs.

**Comment by brylie** [comment] 2016-10-31 12:54
Good work! Lets clean up that hook. :cool: :sunglasses:

**Comment by jykae** [comment] 2016-11-02 10:25
<img width="982" alt="nayttokuva 2016-11-02 kello 12 00 14" src="https://cloud.githubusercontent.com/assets/293452/19925096/32f5320c-a0f7-11e6-983a-faab8455142d.png">

Reason for this according above apinf.io logs:
https://github.com/apinf/platform/blob/0.33.2/users/server/login_verify.js#L15

Current develop, we are checking that: (would explain difference between nightly vs. apinf.io)
https://github.com/apinf/platform/blob/develop/users/server/login_verify.js#L20

**Comment by jykae** [comment] 2016-11-02 10:27
@bajiat @brylie maybe we can close this as solved?

**Comment by brylie** [comment] 2016-11-02 11:53
@jykae we need to verify that it works properly in apinf.io. @bajiat mentioned testing it on staging.apinf.io and then deploying the next release on apinf.io. If things work correctly on apinf.io we can close this issue.

**Comment by jykae** [comment] 2016-11-11 11:06
@bajiat @brylie Tested new release on staging. Verified to work as expected. Closing.
<img width="1180" alt="nayttokuva 2016-11-11 kello 13 03 43" src="https://cloud.githubusercontent.com/assets/293452/20213082/652128ca-a80f-11e6-912a-df10948e8e05.png">

**Closed by jykae** 2016-11-11 11:06 UTC
Labels: bug, ready

**Comment by bajiat** [comment] 2016-11-11 12:08
Also apinf.io looks ok after the new release was deployed. Showing Login forbidden instead of Internal server error
