### ISSUE TITLE
Changing language requires extra click away from language menu

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#2846] opened 2017-08-24 06:15 UTC
# Steps  
1.Visit https://staging.apinf.io  v 0.48.0
2.Change language

# Findings
* Language does not change immediately after selecting one
* You need to click away from the language menu to refresh the site
* Some link don't work while selecting language eg. organizations

# Screenshot 
![kieli](https://user-images.githubusercontent.com/28555452/29652325-a00cfb92-88ad-11e7-815c-b5d4d1e428d8.png)

Here you can see English selected but it still shows finish translations

![kieli2](https://user-images.githubusercontent.com/28555452/29652570-b51c1b66-88ae-11e7-827a-811d322b024b.png)

And same other way around

Tested on 
Admin account
Windows 8
Google chrome latest
staging v 0.48.0

**Comment by marla-singer** [comment] 2017-08-24 07:36
@bajiat Duplicate of #2530
I was working on changing the language. I made that to keep backward compatibility with iOS devices because iOS browsers don't support event "change" just "blur". It means if I will resolve the reported bug then the language changing wouldn't work on iOS devices.

**Closed** 2017-09-08 09:47 UTC
Labels: backlog, bug, duplicate, low hanging fruit
