### ISSUE TITLE
dashboard overview info doesn't match detailed view

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#2977] opened 2017-09-25 08:50 UTC
# Steps 
1.Visit https://staging.apinf.io v 0.50.0  
2.Sign Up  
3.Create new API  and connect to working proxy
4.Call API 
5.Check API in dashboard overview and detailed view
 

# Expected Result  
Information matches both views.

# Actual Result  
Overview shows 0 at successful calls and errors.

# Operating system  
Windows 8

# Browser
- Google Chrome Version latest  

# Screenshot    

![dashboard_overview](https://user-images.githubusercontent.com/28555452/30800269-206a585e-a1e8-11e7-86cc-0fd47c3c2414.png)

![dashboard_detail](https://user-images.githubusercontent.com/28555452/30800349-60188052-a1e8-11e7-985b-98c679a894b9.png)

Here we can see that the API has calls.

# Link
https://staging.apinf.io/analytic/QrFDRyo4N997fYA7q

**Comment by bajiat** [comment] 2017-10-02 08:55
Duplicate of #3003

**Closed** 2017-10-02 08:57 UTC
Labels: bug, Dashboard 2.0, duplicate, planning
