### ISSUE TITLE
Error while editing API Backend

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#780] opened 2016-01-20 12:34 UTC
# Steps
1. Visit https://apinf.io
2. Sign in
3. Select 'API Backends' from menu
4. Add API Backend
5. Go to 'Manage API backends'
6. Click on 'Edit' button
7. Go to Servers field and edit 'Host'
8. Click on 'Submit' button

Actual Result: API Backend was successfully published  
Expected Result: User  has to be notified to edit backend host in  'Host' field as well.
# Operating System
1. Linux : Ubuntu 14.04.03 LTS (Trusty)
2. Windows 10
# Browser
1. Internet explorer 11
2. Mozilla Firefox 44.0 
# Screenshot:

![edit_api_backendhosts_error1](https://cloud.githubusercontent.com/assets/13309358/12448528/45b69ff2-bf7f-11e5-9d6f-695f2c2c630e.png)  

![sucessful_edit_diff_servers_errorpng](https://cloud.githubusercontent.com/assets/13309358/12448902/e96e8342-bf81-11e5-95b8-255671953ecb.png)

**Comment by bajiat** [comment] 2016-01-25 08:19
This is a design decision at API Umbrella level. There can be several servers for one API backend. Hence, it is not a bug, but there could be room for UX enhancement.

**Comment by nnn** [comment] 2016-11-30 15:18
Closing this since we have updated layout of this view.

**Closed by nnn** 2016-11-30 15:18 UTC
Labels: enhancement, icebox, User Experience
