### ISSUE TITLE
Privacy Policy and Terms of Use texts not saving correctly on update

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2238] opened 2017-03-06 10:03 UTC
When updating the Privacy Policy and Terms of Use texts, they do not save correctly. After re-loading the Branding page, the Privacy Policy and Terms of Use fields are empty.

**Comment by nnn** [comment] 2017-03-06 13:12
Couldn't reproduce in the latest develop.
Also tested with resetting project.
@brylie did the same - not reproducible.
Maybe has something to do with [this](https://github.com/apinf/platform/pull/2227) PR being merged.

**Closed by nnn** 2017-03-06 13:12 UTC
Labels: bug, in progress
