### ISSUE TITLE
Footer : Data:  'APIs' title text misplaced

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2592] opened 2017-05-19 08:18 UTC
# Steps  
1.Visit https://staging.apinf.io v 0.44.1  
2.Go to footer 

# Findings 
API data:  Title text 'APIs' must be below the number line   

# Screenshot     
![footer_ apis_title_text_misplaced](https://cloud.githubusercontent.com/assets/13309358/26239219/cf777eae-3c84-11e7-851b-1e5d81f62d29.PNG)

**Comment by 55** [comment] 2017-05-19 08:19
Duplicate of #2493

**Closed** 2017-05-19 08:19 UTC
Labels: duplicate

**Comment by saralavanip** [comment] 2017-06-22 03:52
Verified this resolved issue on https://staging.apinf.io v 0.46.0 and it is not reproducible.
