### ISSUE TITLE
Swagger rendering issue with ampersand

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2200] opened 2017-02-27 12:11 UTC
I have designed an API in [swaggerhub](https://app.swaggerhub.com/api/kyyberi/APInf-REST-API/MVP). Then I export it to JSON and import it to apinf.io. Things go smooth otherwise, but when I write call examples, ampersand misbehaves. In those cases "&" is not decoded, but appears as "amp;". 

I tested this by writing the ampersand both ways: 

In exported JSON file, the examples look like

``` 
Example call: GET /apis?limit=200&lifecycle=production 
Example call: GET /apis?limit=200&amp;lifecycle=production
```

In apinf.io the documentation looks like below:
![bug-viewer](https://cloud.githubusercontent.com/assets/1927158/23360893/83f8c4a6-fcf6-11e6-827c-26b303e45a74.png)

How should I write ampersand to make it pretty?  :)

**Comment by brylie** [comment] 2017-02-27 12:22
This is a security feature of the templating language, where it automatically escapes HTML characters. Also, we no longer include examples of `GET` calls, since they are inherently insecure. Our apinf.io production website has not received recent updates yet, so we should try and reproduce this issue on nightly.apinf.io.

**Comment by kyyberi** [comment] 2017-02-27 12:47
"we no longer include examples of GET calls, since they are inherently insecure." Say what? We exclude all GET method calls from APIs? How do you list things with API then? I don't quite follow now.

**Comment by kyyberi** [comment] 2017-02-27 12:48
I'll try on nightly.

**Comment by kyyberi** [comment] 2017-02-27 12:51
Problem prevails

![bug-viewer-nightly](https://cloud.githubusercontent.com/assets/1927158/23361991/32abe94c-fcfc-11e6-9508-c56727996742.png)

**Comment by brylie** [comment] 2017-02-27 12:53
@kyyberi can you include a larger screenshot, showing the entire web page? It is hard to see the full context of this issue.

**Comment by kyyberi** [comment] 2017-02-27 12:55
![screenshot at helmikuuta 27 14-54-52](https://cloud.githubusercontent.com/assets/1927158/23362085/bf2213a6-fcfc-11e6-879a-1ce721f5b666.png)

![screenshot at helmikuuta 27 14-54-27](https://cloud.githubusercontent.com/assets/1927158/23362088/c491c002-fcfc-11e6-84b8-c1c57cb49d2a.png)

**Comment by brylie** [comment] 2017-02-27 13:17
OK, thanks. We should probably ask for support in the upstream Swagger UI project, since it is responsible for correctly rendering the Swagger file.

**Comment by brylie** [comment] 2017-02-27 13:23
I opened an [upstream support request](https://github.com/swagger-api/swagger-ui/issues/2700).

**Comment by marla-singer** [comment] 2017-03-17 07:39
Searched the same issues, found one [open PR](https://github.com/swagger-api/swagger-ui/issues/2225). The problem is that the sanitization is happening twice for ampersand symbol.
1. & -> &amp;
2. &apm; -> &amp;amp;
3. &amp;amp; -> &amps; (after render)
This situation is repeated only for an ampersand. Other symbols were not sanitized twice.
Maybe Swagger library parsed and it incorrect or problem came from 3rd library (marked.js or sanitize.js)

**Comment by marla-singer** [comment] 2017-04-07 08:43
@kyyberi @brylie Verified this issue in Swagger v3.0.It's resolved in new version
![joxi_screenshot_1491554513307](https://cloud.githubusercontent.com/assets/20643403/24792580/536432ee-1b87-11e7-92a6-8b7b76c180fd.png)

**Comment by marla-singer** [comment] 2017-05-26 15:22
@bajiat We can close it because that was resolved also on apinf.io site because we are using a new Swagger UI

**Closed** 2017-07-04 14:22 UTC
Labels: bug, icebox
