### ISSUE TITLE
Dashboard onload - dont load first statistics

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2459] opened 2017-04-17 07:03 UTC
## Description

When user goes to dashboard, it automatically starts loading statistics for first API in the list. I do not want to wait until that is done to select API I actually want to see. 

## Fix 
Don't autoload any stats for any API. Let user select API to discover.

**Comment by marla-singer** [comment] 2017-09-07 12:00
@kyyberi @bajiat Have to be fixed in anew Dashboard page

**Comment by marla-singer** [comment] 2017-12-07 09:32
@preriasusi Already done with new Dashboard. The issue is outdated

**Closed** 2017-12-08 09:19 UTC
Labels: backlog, Usability Issue
