### ISSUE TITLE
Dashboard page is blank in nightly

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2301] opened 2017-03-16 08:03 UTC
# Steps to reproduce
1. Log in as admin or API owner to nightly.apinf.io
2. Press Dashboard link

# Expected result
You are able to select an API for viewing

# Actual result
You see a blank page with only the title Dashboard

# Screenshot
<img width="607" alt="empty dashboard" src="https://cloud.githubusercontent.com/assets/11626388/23987056/1fda4e8a-0a30-11e7-9a7f-719a1e35677f.png">

**Comment by brylie** [comment] 2017-03-16 08:08
cc: @marla-singer

**Comment by marla-singer** [comment] 2017-03-16 08:09
@brylie It is a duplicate of #2268. It has not been resolved yet.

**Comment by marla-singer** [comment] 2017-03-16 08:12
@bajiat It is repeated only for Admin. As API Manager I can see Dashboard page correct
![joxi_screenshot_1489651853436](https://cloud.githubusercontent.com/assets/20643403/23987190/68121490-0a39-11e7-8127-f47e66ec546f.png)

**Comment by brylie** [comment] 2017-03-16 08:13
Closing as duplicate.

**Closed by brylie** 2017-03-16 08:13 UTC
Labels: bug, planning
