### ISSUE TITLE
IE: Clicking on Add organization button on Organization Details dialog throws error. Organization can't be add

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#3282] opened 2017-12-20 14:02 UTC
**Steps to Reproduce**: 
1. go to vamos deployment and login as platform admin
2. Click Organization
3. Click Add Organization
4. provide necessary details in the dialog and click Add
                    
**Outcome**:
organization can't be added.
browser console shows the following error.
http://recordit.co/GKdVyDj1ir
         
**Expected Behavior**:
Organization should be possible to add.
User should be redirected to organization profile
console should have no error message
                   
**Environment**:

Windows 10, IE11, release (0.52)

**Comment by deligence-dharmendra** [comment] 2018-01-10 07:45
Hi @preriasusi @Nazarah,
I have tested the issue on the Windows 7 and Windows 10 using my local development system. but did not get any issue. Test environment and the screenshot are given below.
~~~
Window 7, IE 11 and Google Chrome
Windows 10, IE 11 and edge 40
~~~
![add new organization edge 40](https://user-images.githubusercontent.com/32898978/34761041-2b373710-f608-11e7-8a2d-835564c7a8ba.png)
![add new organization edge 40 win 10](https://user-images.githubusercontent.com/32898978/34761042-2b72e1c0-f608-11e7-8bce-716cba9cbfe8.png)
![add new organization win 10 ie 11](https://user-images.githubusercontent.com/32898978/34761043-2bae29b0-f608-11e7-9e85-fad0ec6d6722.png)
![add organization win7 ie 11](https://user-images.githubusercontent.com/32898978/34761047-2be98528-f608-11e7-89c6-667656002c1d.png)
![add organization win 7 chrome](https://user-images.githubusercontent.com/32898978/34761049-2c23d9f8-f608-11e7-98fe-7ef6a8fc94d0.png)

**Comment by marla-singer** [comment] 2018-01-10 09:28
@matleppa Can you please also test it in IE?

**Comment by matleppa** [comment] 2018-01-10 11:44
2018-01-10
Win 10
IE 11.192.16299.0
vamos.apinf.io, Apinf 0.52.0 

Could not reproduce the error.

**Comment by marla-singer** [comment] 2018-01-11 08:00
Closed it as not reproduced by other devs and can't be fixed
Need more details about bug

**Closed by marla-singer** 2018-01-11 08:00 UTC
Labels: IE bug, Team DLG, bug, in progress
