### ISSUE TITLE
Refresh 'Suomi' page view changes to 'English' 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#880] opened 2016-02-17 07:43 UTC
# Steps
1. Visit https://nightly.apinf.io  
2. Login  
3. Change language to 'Suomi'  
4. Go to dashboard  
5. Refresh/reload page  
# Findings

 'Suomi' page view changes to 'English'  language view.

**Comment by saralavanip** [comment] 2016-11-03 11:59
@bajiat , verified this issue on https://nightly.apinf.io and it is reproducible.

**Comment by bajiat** [comment] 2017-02-10 14:29
@saralavanip This error should not be reproducible because of the recent changes with refresh (#258). Please verify.

**Comment by saralavanip** [comment] 2017-02-13 11:00
@bajiat , verified this resolved issue on https://nightly.apinf.io   v 0.40.0 and it is not reproducible.

**Comment by bajiat** [comment] 2017-02-13 13:55
@saralavanip Thanks. Closing the issue.

**Closed by bajiat** 2017-02-13 13:55 UTC
Labels: bug, icebox
