### ISSUE TITLE
Unable to disable API key requirement for API

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#3189] opened 2017-12-04 17:09 UTC
**Steps to Reproduce**: 
1. go to page: https://apinf.io/apis/lipas-api
2. go to proxy tab.
3. Click "Disable API key requirement" on. 
4. Click "Save & publish"
                    
**Outcome**:
Save fails and error is shown: 
<img width="370" alt="error-disable-api-key" src="https://user-images.githubusercontent.com/1927158/33565638-579657a4-d926-11e7-89bf-49fe60f3f8d1.png">

Perhaps this is related to fact that API does not support HTTPS. 
<img width="916" alt="screenshot at jouluk 04 19-07-02" src="https://user-images.githubusercontent.com/1927158/33565670-709a0b88-d926-11e7-9e30-bbcb1139c581.png">

**Note, I was able to connect proxy and then wanted to disable the API key requirement. So this is change/update process.**
         
**Expected Behavior**:

Save settings and show user a notification that all went well. API key should not be required in the next API calls in this API. 
                   
**Environment**:

MacOS, FF Quantum (57.0.1), APInf production site (https://apinf.io)

**Comment by marla-singer** [comment] 2017-12-05 07:56
Close it as duplicate of #3090. Will be resolved in 0.51.0 release

**Closed by marla-singer** 2017-12-05 07:56 UTC
Labels: bug

**Comment by kyyberi** [comment] 2017-12-05 10:43
I resent the pre close of bugs. This bug is in production until new release is out there. It is not solved. Until that it's there preventing endusers to use system as it should be used. 

Up to PO to decide @preriasusi

**Comment by marla-singer** [comment] 2017-12-05 10:46
This issue is a duplicate. You already reported this bug with the same title and I even specified the number of issue
