### ISSUE TITLE
"Swagger document is not valid" after updating apiDoc

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2296] opened 2017-03-15 13:29 UTC
Early nightly.apinf.io site has the APIs with uploaded Swagger documentation. About month ago we implemented the new version of Documentation Manage dialog which allows adding Swagger documentation both File and URL. 

Now it displays"Swagger document is not valid" with the old correct documentation. I changed the type to File and the Swagger UI was updated after refreshing.

Verified on nigthly.apinf.io (v 0.41.0)
![joxi_screenshot_1489590896408](https://cloud.githubusercontent.com/assets/20643403/23955563/55015fac-09ab-11e7-86dd-f37ba7f26c43.png)

### Suggested reason
It happened because of the incorrect migration. [We have to specify](https://github.com/apinf/platform/blob/develop/core/migrations/server/3-move-api-docs.js#L15-L20) the `type: "file"` as well

**Comment by kyyberi** [comment] 2017-03-17 06:50
I get that in production now. https://apinf.io/apis/gRckL9iXKXSvJDeyb

**Comment by bajiat** [comment] 2017-03-17 07:48
Should this be hotfixed to production once it has been fixed?

**Comment by bajiat** [comment] 2017-03-20 12:48
@marla-singer Can you mentor @nnn in this task? Or even be assigned to this task?

**Comment by marla-singer** [comment] 2017-03-20 13:09
@bajiat Yes, I can mentor. If @nnn will have the problem with it, I would be able to take this task on the next week. Is it okay?

**Comment by marla-singer** [comment] 2017-03-27 13:16
@nnn Do you need some help or advice with this task?

**Comment by jawidahmadi** [comment] 2017-05-02 12:53
@marla-singer I added a sample.yaml (http://sample-file.bazadanni.com/2015/02/yaml.html)  file in develop stage, however, i could not reproduce the same bug. Could you kindly add the steps to reproduce the bug?

**Comment by marla-singer** [comment] 2017-05-02 13:51
@jawidahmadi Run 40 version on local, add API + swagger file, update your project to the current version and make the migration.
The problem happens when site had the old structure collection and API had an uploaded swagger file

**Comment by marla-singer** [comment] 2017-05-02 14:17
@jawidahmadi Now the problem looks like 
https://nightly.apinf.io/apis/test-vision1-api
https://nightly.apinf.io/apis/weather-api
It happens (as I think) because apiDocs documenta contains field `fileId` and has `tyle: 'url'`

**Closed** 2017-05-09 12:35 UTC
Labels: bug, Documentation Viewer 2.0, Ready for review
