### ISSUE TITLE
Api Catalog filter options showing as English when Suomi language is selected

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2101] opened 2017-02-10 09:36 UTC
On the API Catalog, the 'Filter by' options are showing as English when Suomi language is active:

![screenshot_20170210_112714](https://cloud.githubusercontent.com/assets/17307/22821763/33181704-ef85-11e6-8d86-cd4b584f934f.png)

**Comment by marla-singer** [comment] 2017-02-10 09:37
Duplicate of #2046

**Closed** 2017-02-10 09:44 UTC
Labels: duplicate, enhancement, i18n/l10n
