### ISSUE TITLE
Site title shown as 'Project logo'

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1505] opened 2016-09-08 08:14 UTC
- Local development environment 

Steps: 
1.Login as admin   
2.Navigate to Branding section   
3.Do not upload project logo  
3.Enter Site title    
4.Enter Site slogan    
5.Click on 'Update' button  

Findings: 
- Site title is shown as project logo  

Expected Result: Project logo should not be replaced with site title     

Browser:   
1. Mozilla Firefox 48.0 
(Mozilla Firefox for Ubuntu Canonical – 1.0 )   
2. Google Chrome 52.0.2743.116  

Operating System:  
1. Ubuntu 16.0 LTS

Screenshot:    
![site_title_project_logo](https://cloud.githubusercontent.com/assets/13309358/18341920/10b8ce96-75b5-11e6-9720-aedebd450e18.png)

**Comment by bajiat** [comment] 2016-10-20 12:35
This is a feature, not a bug. Closing this issue.

**Closed** 2016-10-20 12:35 UTC
Labels: bug, icebox, wontfix
