### ISSUE TITLE
Admin dashboard shows empty page 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2294] opened 2017-03-14 15:44 UTC
# Steps 
1.Visit https://nightly.apinf.io   (v 0.41.0)  
2.Login as admin 
3.Go to Dashboard  

# Findings 
shows empty page 

# Screenshot    
![nightly_admin_dashboard_empty_page](https://cloud.githubusercontent.com/assets/13309358/23908831/bdaddb1c-08dd-11e7-8f66-2f9939a932d7.PNG)

**Comment by marla-singer** [comment] 2017-03-15 07:12
Duplicate of #2268. Close it

**Closed by marla-singer** 2017-03-15 07:12 UTC
Labels: bug
