### ISSUE TITLE
API profile: popover text doesn't have translation

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2013] opened 2017-02-03 12:13 UTC
Verified on nightly.apinf.io (0.39.0 version)
API profile -> Documantation tab -> Manage button

![joxi_screenshot_1486123942225](https://cloud.githubusercontent.com/assets/20643403/22590988/51cccf76-ea23-11e6-9a97-cc7368a025d8.png)

**Comment by bajiat** [comment] 2017-02-06 07:30
@marla-singer Are the srings included in the English i18n file?

**Comment by marla-singer** [comment] 2017-02-06 12:40
@bajiat Checked it. Yes, they are but don't work as expected

**Comment by marla-singer** [comment] 2017-02-18 15:12
@bajiat Interested

**Comment by marla-singer** [comment] 2017-02-20 11:50
@bajiat I fixed the tags. Please check that translation is correct for tags:
- "manageApiDocumentationModal_hints_uploadApiDocumentation"
- "manageApiDocumentationModal_hints_documentation_link"

**Comment by jawidahmadi** [comment] 2017-02-27 07:28
There is no active support to the  package that is used for this purpose. According to the localization document, the implementation is correct  . But, the local language is not displayed.

**Comment by marla-singer** [comment] 2017-02-27 07:29
@jawidahmadi Look commit https://github.com/apinf/platform/pull/2121/commits/25dab0a0968e44652fe655b16742769b05be0a6e

**Comment by jawidahmadi** [comment] 2017-02-27 10:08
@marla-singer I checked this issue. It is fixed in feature/swagger-url branch.

**Comment by brylie** [comment] 2017-02-27 10:21
cc: @nnn this is related to your work in the API Documentation re-write.

**Comment by marla-singer** [comment] 2017-02-27 10:28
@brylie This issue was taken by @jawidahmadi PR #2190

**Comment by jawidahmadi** [comment] 2017-02-27 10:30
Closes #2013

**Comment by brylie** [comment] 2017-02-27 10:36
> @brylie This issue was taken by @jawidahmadi PR #2190

@marla-singer as you commented above, you resolved this issue with a commit to @nnn's branch. Hence, I assigned you to the issue and pinged @nnn, since the issue is resolved in your pair-programming work.

**Comment by marla-singer** [comment] 2017-02-27 10:38
@brylie Yes. But I think it should be done in separate branch because @nnn is doing the big work in his PR

**Comment by brylie** [comment] 2017-02-27 10:45
> I think it should be done in separate branch

This is something that needs to be worked out between you (@marla-singer), @nnn and @jawidahmadi.

**Comment by jawidahmadi** [comment] 2017-02-27 13:11
@brylie @marla-singer @nnn  I have added the fix in popover-translation branch. It is ready for review.

**Comment by nnn** [comment] 2017-02-27 13:21
@marla-singer that's already fixed in #2121, so there's no need to create an another PR for this.

**Comment by marla-singer** [comment] 2017-02-27 13:23
@nnn Oh, yeah, sorry. Didn't think that you will continue work in current branch.

**Closed** 2017-03-01 13:19 UTC
Labels: bug, i18n/l10n, in progress
