### ISSUE TITLE
Identify key elements of SaaS service monetization

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2130] opened 2017-02-16 14:10 UTC
Create a mindmap about Saas sevice monetization to identify the key elements related to both admins and API owners and potential other users. At this stage, this can be needs or actions etc.

**Comment by mauriciovieira** [comment] 2017-05-19 19:47
Would this be an EPIC? @bajiat @philippeluickx @kyyberi

**Comment by mauriciovieira** [comment] 2017-05-19 19:53
Or is it a duplicate of #1852 ?

**Comment by philippeluickx** [comment] 2017-05-22 06:59
I believe this is a research task that is part of the #1852 epic.

**Closed** 2018-08-20 08:37 UTC
Labels: SaaS service monetization, icebox
