### ISSUE TITLE
Feedback view: Successful send 'Feedback' shows incorrect time stamp

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2879] opened 2017-09-04 06:14 UTC
# Steps  
1.Visit https://staging.apinf.io v 0.49.0  
2.Sign In 
3.Go to 'APIs' catalog 
4.Click on any API 
5.Go to 'Feedback' view and click on 'Send Feedback' 
6.Fill the feedback form and click on 'Send' button 

# Findings 
Successful send feedback report shows incorrect time stamp. By default it shows sent " in 3 hours"   

# Browser 
Chrome Version 60.0.3112.113 (64-bit)

# Operating system 
Windows 10 

# Screenshot   
![feedback_incorrect_timestamp](https://user-images.githubusercontent.com/13309358/30013777-2a39490a-9151-11e7-9bec-996699f8992b.PNG)

**Comment by marla-singer** [comment] 2017-09-04 10:17
@saralavanip Can you provide your local time in UTC? I suppose you have UTC+6

**Comment by saralavanip** [comment] 2017-09-04 10:30
@marla-singer , It is UTC+5:30

**Comment by marla-singer** [comment] 2017-09-04 10:32
Although I tested it on Debain with UTC+6 time and couldn't repeat.
Maybe It happens on Windows
![joxi_screenshot_1504521074011](https://user-images.githubusercontent.com/20643403/30022776-7e0ed134-9175-11e7-9eb4-d575ae0f1b05.png)

**Comment by bajiat** [comment] 2017-09-05 06:55
I tested in Windows 10 / Chrome and could not reproduce the bug. 

1. Add feedback

![2879_SendFeedback.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/551116a6d52f6a7100417fce/125516c66e82c728ace21e0d46bacccd7abdb0ac81ed9946a159f2952a4d653f6b14b1247a80e03cfd1839545a5d4dfe145c0b44faad8c29afb33f708a0a0aea876a5a66da2f53fde6d640e258f075c95d8fa4bd8d46c1ed3d21e2828b4b3d1f051e81ed10.PNG)

2. Check timestamp

![2879_CheckTimestamp.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/551116a6d52f6a7100417fce/125516c66e82c728ace21e0d46bacccd7abda0a18aeab477ad50f5873d472a636b48e13b628ae92dbc56395b4d5a4bae420a0a40a8f98f7fa3b43575895c0bbbd06a0973c32f0dbefad341eb5ee779c11ac7a4b6984dc7e23c20e78f8a463a1a001a81fd5427ed.PNG)

**Comment by saransh-dev** [comment] 2017-09-30 06:29
Hi

I have submit a feedback on `Geocode API` and it shows `few seconds ago`.

Operating System: MAC OS
Browser: FireFox and Chrome

Please check below screenshot:-
<img width="1280" alt="feedback" src="https://user-images.githubusercontent.com/29011434/31043261-9d86a4ea-a5d6-11e7-9c47-a88a44f42f83.png">


Thanks & Regards,
Saransh

**Comment by bajiat** [comment] 2017-10-16 12:25
Closing, since it was not possible to reproduce the error.

**Closed by bajiat** 2017-10-16 12:25 UTC
Labels: bug, in progress
