### ISSUE TITLE
Nightly: Can't upload jpeg image as cover photo in the site

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2354] opened 2017-03-23 10:25 UTC
Tried to upload a picture taken on monday photo session.
The picture format is jpeg.
On selecting the picture from desktop, S-alert appears mentioning the supported format.
Picture doesn't get uploaded at all

**Comment by bajiat** [comment] 2017-03-23 12:29
I was able to upload a cover picture from the same photo session (jpg, 630 kB).

**Comment by bajiat** [comment] 2017-03-24 07:23
@Nazarah @marla-singer 
Since this is not a bug and a photo can be uploaded, should we close this? Do you want to open another issue for any size restrictions or user texts?

**Comment by marla-singer** [comment] 2017-03-24 07:32
As for me, we can close it

**Comment by Nazarah** [comment] 2017-03-24 07:36
closing the issue. A related usability issue is reported in #2357

**Closed** 2017-03-24 07:36 UTC
Labels: bug
