### ISSUE TITLE
Create Account: Username with underscore shows error

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2266] opened 2017-03-09 09:07 UTC
# Steps 
1.Visit https://staging.apinf.io   (v 0.41.0 )   
2.Click on 'Sign up'     
3.Enter valid Username  (eg.  abc_test1 )  
4.Enter valid Email and Password  
5.Click on 'Register'    
  
# Expected Result  
Successful creating account 

# Actual Result  
Shows error message though username with underscore is allowed  

# Screenshot  
![signup_underscore_error](https://cloud.githubusercontent.com/assets/13309358/23743086/fcdb1ae0-04b7-11e7-92f3-4333ba9d6335.PNG)

**Comment by marla-singer** [comment] 2017-03-09 09:14
@saralavanip Duplicate of #1963

**Comment by snittoor** [comment] 2017-03-09 09:57
@saralavanip : I am working on this one #1985

**Comment by bajiat** [comment] 2017-03-13 11:23
Closing as duplicate

**Closed** 2017-03-13 11:23 UTC
Labels: bug
