### ISSUE TITLE
Uncaught Error: Configuration options must be set before AccountsTemplates.init!

### ISSUE THREAD

**Issue by manzapanza** [apinf/platform#2340] opened 2017-03-20 11:33 UTC
Running the project locally for development purposes, when save a file, the app is automatically refreshed and sometimes these errors appear in the console:

```
There is no route for the path: /
kadira_flow-router.js?hash=8336ad1…:519 

Uncaught Error: Configuration options must be set before AccountsTemplates.init! 
useraccounts_core.js?hash=265f0c0…:842 
```

Only killing the app and start again the error disappear.

The full error message:

```
kadira_flow-router.js?hash=8336ad1…:519There is no route for the path: /
Router._notfoundRoute @ kadira_flow-router.js?hash=8336ad1…:519
(anonymous) @ kadira_flow-router.js?hash=8336ad1…:707
(anonymous) @ kadira_flow-router.js?hash=8336ad1…:1490
nextEnter @ kadira_flow-router.js?hash=8336ad1…:1322
(anonymous) @ kadira_flow-router.js?hash=8336ad1…:1491
nextEnter @ kadira_flow-router.js?hash=8336ad1…:1322
(anonymous) @ kadira_flow-router.js?hash=8336ad1…:1491
nextEnter @ kadira_flow-router.js?hash=8336ad1…:1322
(anonymous) @ kadira_flow-router.js?hash=8336ad1…:1491
nextEnter @ kadira_flow-router.js?hash=8336ad1…:1322
(anonymous) @ kadira_flow-router.js?hash=8336ad1…:1491
nextEnter @ kadira_flow-router.js?hash=8336ad1…:1322
(anonymous) @ kadira_flow-router.js?hash=8336ad1…:1491
nextEnter @ kadira_flow-router.js?hash=8336ad1…:1322
(anonymous) @ kadira_flow-router.js?hash=8336ad1…:1491
nextEnter @ kadira_flow-router.js?hash=8336ad1…:1322
(anonymous) @ kadira_flow-router.js?hash=8336ad1…:1491
nextEnter @ kadira_flow-router.js?hash=8336ad1…:1322
(anonymous) @ kadira_flow-router.js?hash=8336ad1…:1491
nextEnter @ kadira_flow-router.js?hash=8336ad1…:1322
page.dispatch @ kadira_flow-router.js?hash=8336ad1…:1328
page.replace @ kadira_flow-router.js?hash=8336ad1…:1291
self._page.(anonymous function) @ kadira_flow-router.js?hash=8336ad1…:554
page.start @ kadira_flow-router.js?hash=8336ad1…:1184
page @ kadira_flow-router.js?hash=8336ad1…:1118
Router.initialize @ kadira_flow-router.js?hash=8336ad1…:563
FlowRouter.initialize @ useraccounts_flow-routing.js?hash=3e4b855…:581
(anonymous) @ router.js:25
Tracker.Computation._compute @ tracker.js?hash=9f8a0ce…:339
Tracker.Computation @ tracker.js?hash=9f8a0ce…:229
Tracker.autorun @ tracker.js?hash=9f8a0ce…:604
meteorInstall.core.client.lib.router.js @ router.js:17
fileEvaluate @ modules-runtime.js?hash=0969a31…:207
require @ modules-runtime.js?hash=0969a31…:130
(anonymous) @ app.js?hash=f27f4ee…:51462


useraccounts_core.js?hash=265f0c0…:842 Uncaught Error: Configuration options must be set before AccountsTemplates.init!
    at AT.configure (useraccounts_core.js?hash=265f0c0…:842)
    at meteorInstall.users.client.lib.accounts_config.js (accounts_config.js:11)
    at fileEvaluate (modules-runtime.js?hash=0969a31…:207)
    at require (modules-runtime.js?hash=0969a31…:130)
    at app.js?hash=f27f4ee…:51473
```

**Comment by brylie** [comment] 2017-03-24 07:35
We might need to need to wrap the [accounts configuration code](https://github.com/apinf/platform/blob/develop/users/client/lib/accounts_config.js#L11) in a [Meteor.startup()](https://docs.meteor.com/api/core.html#Meteor-startup).

Alternatively, since you are noticing this when rebuilding the project during development, Meteor might be 'caching' some of the application files/state during hot-reload. Please open an upstream support request with [Meteor useraccounts](https://github.com/meteor-useraccounts/core) to see if anyone else is having this trouble.

**Comment by brylie** [comment] 2017-03-24 07:44
@manzapanza can you please provide us with steps to reproduce this issue?

**Comment by marla-singer** [comment] 2017-05-02 13:25
Close it as duplicate of #2465 which provides more details about this bug

**Closed** 2017-05-02 13:25 UTC
Labels: bug, duplicate, icebox
