### ISSUE TITLE
Unable to upload documentation file

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#1646] opened 2016-09-27 10:58 UTC
On nightly.
Add a new API backend.
Go to documentation tab. Select manage. Select a sample json file to upload.
Unable to upload documentation for an API I own:

```
File creation failed! n {error: 403, reason: "Access denied", details: undefined, message: "Access denied [403]", errorType: "Meteor.Error"}
```

**Comment by philippeluickx** [comment] 2016-09-27 11:06
Also unable to upload logo
```
File creation failed! n {error: 403, reason: "Access denied", details: undefined, message: "Access denied [403]", errorType: "Meteor.Error"}
```

**Comment by bajiat** [comment] 2016-09-27 11:12
@marla-singer Can you take a look at this?

**Comment by marla-singer** [comment] 2016-09-27 11:34
@bajiat It's dublicate this issue #1570. I researched and detected that only users, who has a role 'admin' or 'manager', can upload a file. User doesn't have ane role on default. It can be solved in two ways:
1. Administrator can share role 'manager' to user
2. Or someone fixes it on code - if user add an api, will give him 'manager' role

**Comment by bajiat** [comment] 2016-09-27 11:43
@marla-singer It is true that user  does not have any role by default. But when they add an API, they become a manager automatically - but only for that particular API. This should already work, unless there is regression. 
@philippeluickx added an API, thus becoming a 'manager' for that API.  The same thing in #1570, @saralavanip started by adding an API.

**Comment by marla-singer** [comment] 2016-09-27 11:46
@bajiat It looks like users don't become a manager automatically.

**Comment by bajiat** [comment] 2016-09-27 14:26
@brylie Can you check this - do we have a regression and user does not become a manager if they add an API? Or is it related to adding Swagger files only?

**Comment by philippeluickx** [comment] 2016-09-28 11:56
@bajiat It is also for uploading the logo, so I would assume that @marla-singer is correct in her assumption.

**Comment by brylie** [comment] 2016-09-29 10:45
@bajiat, @marla-singer is correct that [only users with Manager or Admin role can upload API Documentation files](https://github.com/apinf/platform/blob/develop/documentation/collection/server/permissions.js#L5). We can add a one-line fix for this issue, so that when they create an API they are assigned the 'manager' role.

```js
// in apis/client/add/autoform.js
onSuccess (formType, apiId) {
      ...

      // Get current user ID
      const userId = Meteor.userId();

      // Give user manager role
      Roles.addUsersToRoles(userId, 'manager');
    }
```

We will also need an Allow rule for the Roles collection

```js
// in /users/collection/roles_permissions.js
Meteor.roles.allow({
  insert () {
    return true;
  },
});
```

**Comment by brylie** [comment] 2016-09-29 10:46
As a more future-proof step, we could write a server-side method to run in autoform onSuccess, using the [Validated Methods](https://guide.meteor.com/methods.html#validated-method) package.

**Comment by brylie** [comment] 2016-09-29 10:50
This is a kind of tricky situation. On one hand, `FileCollection` package relies on collection allow/deny rules, so it may not be easy to create a ValidatedMethod for the `FileCollection` insert.

The alternative would be to create a ValidatedMethod where we add the user to the 'managers' role.

What other options do you see @marla-singer?

**Comment by brylie** [comment] 2016-09-29 11:10
I created a quick PR to resolve this issue. Instead of using the allow/deny approach for the Roles collection, I simply add the 'manager' role on startup. Then, when users create an API, they are given the 'manager' role.

**Comment by marla-singer** [comment] 2016-09-29 11:14
> I created a quick PR to resolve this issue.
Instead of using the allow/deny approach for the Roles collection, I simply add the 'manager' role on startup. Then, when users create an API, they are given the 'manager' role.

I think it's a good solution at the moment

**Comment by brylie** [comment] 2016-09-29 11:23
@marla-singer thanks. Will you please review the PR #1660?

**Comment by marla-singer** [comment] 2016-09-29 11:27
@brylie Yes. I'll also test if these fixes the problem with uploading a logo

**Closed** 2016-09-29 11:35 UTC
Labels: bug, in progress
