### ISSUE TITLE
Suomi view: Organization cards misaligned in Firefox browser 

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2425] opened 2017-04-07 07:27 UTC
# Steps  
1.Open Firefox browser and Visit https://nightly.apinf.io   (v 0.42.0)   
2.Go to Organizations 
3.Change language to  'Suomi' 

# Findings  
Organization cards misaligned in grid view 

# Browser 
Mozilla Firefox  v 52.0.2    

# Operating system 
Windows 10   

# Screenshot   
![organizations_misaligned_suomi_view](https://cloud.githubusercontent.com/assets/13309358/24789580/6271c806-1b7c-11e7-9208-c05e316cae0c.PNG)

**Comment by marla-singer** [comment] 2017-04-07 08:52
Duplicate of #2205

**Closed** 2017-04-07 09:22 UTC
Labels: duplicate
