### ISSUE TITLE
API Catalog Cardview: APIs with long description texts get scrambled in card view

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1769] opened 2016-10-12 11:00 UTC
# Reproduction steps:
* go to https://staging.apinf.io/catalogue
* go to an API profile-> Setting tab
* Add and save the following text in Description field: Попробуйте сделать следующее: Проверьте подключение к Интернету. Проверьте настройки прокси-сервера и брандмауэра.
* Go to catalog

# Result:
* the text gets scrambled with bookmark action and time of the API creation
* Chrome  
![image](https://cloud.githubusercontent.com/assets/17976243/19307601/0a608892-9084-11e6-9343-c712dafb38c5.png)
* IE11
![image](https://cloud.githubusercontent.com/assets/17976243/19307604/0f51942c-9084-11e6-849c-06fe6936c924.png)

# Expected Result:
* the text should not collide with bookmark and creation time text
* for long texts, last few words can appear as faded with "..." to indicate there is more

# Testing environment:
* OS: windows 8
* Browser: any

**Comment by bajiat** [comment] 2016-10-12 11:45
Duplicate of #1757. Closing.

**Closed** 2016-10-12 11:45 UTC
Labels: bug, duplicate
