### ISSUE TITLE
Add logging capabilities

### ISSUE THREAD

**Issue by brylie** [apinf/platform#615] opened 2015-11-11 12:26 UTC
# User story

```
As a system administrator
I would like to review log files for the Apinf platform
so that I can identify issues, warnings, etc. and take corrective action
```
# Feature

Research and choose a logging framework for Apinf (Meteor.js). Add the logging framework/package. Determine what functions, e.g. server methods, need logging support and add calls to the logger with relevant details.

Once logging is enabled, it will be useful to log errors (e.g. within try/catch statements).
# Research

The Winston logging library may be a good solution:
- [Meteor Winston](https://atmospherejs.com/votercircle/winston)
- [Winston Client](https://atmospherejs.com/brentjanderson/winston-client)
# Related
- Issue #636 describes error handling within the `syncApiBackends` method.
- Issue #638 purposes adding an error log to the aplication

**Comment by bajiat** [comment] 2017-03-29 11:12
Closing as duplicate of #638. Description copied to the other issue.

**Closed by bajiat** 2017-03-29 11:12 UTC
Labels: backlog, enhancement
