### ISSUE TITLE
Organization cards misaligned in Suomi view

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2205] opened 2017-03-01 12:14 UTC
# Steps    
1.Visit https://nightly.apinf.io  v 0.41.0
2.Navigate to organizations   
3.Change language to 'Suomi'   

# Result 
Organization cards gets misaligned     

# Screenshot  
![suomi_view_org_catalog](https://cloud.githubusercontent.com/assets/13309358/23459462/0f2948be-fe89-11e6-94cf-babb875b88be.PNG)

**Comment by bajiat** [comment] 2017-03-23 08:46
@saralavanip I'm not able to reproduce this in nightly or in staging with Chrome. In which browser does this happen? Can you add the info to the steps to reproduce?

**Comment by marla-singer** [comment] 2017-03-23 09:54
@bajiat It happens when the date is "Add 7 days ago" as I remember.

**Comment by bajiat** [comment] 2017-03-23 11:07
Ok, so the "added ... ago" text becomes too long in Finnish? Interesting.

**Comment by marla-singer** [comment] 2017-03-23 11:28
Nope. Just 7,8,9,10 digits contain a lot of char in a word. Because of incorrect mark up it is so

**Comment by saralavanip** [comment] 2017-03-23 11:28
@bajiat , Yes, re-tested on nightly and staging not reproducible. 
Currently the Organization Card's status text  'Added ..days ago'  is updated  and might be issue as mentioned by @marla-singer .

**Comment by bajiat** [comment] 2017-03-24 07:38
@marla-singer That is exactly what I meant. When the word for the number is too long, the text becomes too long.

**Comment by bajiat** [comment] 2017-05-11 07:55
@saralavanip Is this bug still relevant with the new organization card style?

**Comment by saralavanip** [comment] 2017-05-11 08:05
@bajiat , Verified on staging v 0.44.0 and it is not reproducible with new organization card style.

**Comment by bajiat** [comment] 2017-05-12 13:01
Closing as resolved.

**Closed** 2017-05-12 13:01 UTC
Labels: bug
